import re
from typing import Iterable, List, Set

# Curated skill surface forms across tech, business, design, finance, ops.
SKILL_TERMS = {
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "go",
    "golang",
    "php",
    "ruby",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "terraform",
    "ansible",
    "linux",
    "unix",
    "bash",
    "powershell",
    "git",
    "jira",
    "confluence",
    "html",
    "css",
    "react",
    "angular",
    "vue",
    "node",
    "node.js",
    "express",
    "django",
    "flask",
    "fastapi",
    "spring",
    "spring boot",
    "machine learning",
    "deep learning",
    "nlp",
    "pytorch",
    "tensorflow",
    "keras",
    "scikit-learn",
    "pandas",
    "numpy",
    "data analysis",
    "data visualization",
    "power bi",
    "tableau",
    "excel",
    "vba",
    "salesforce",
    "sap",
    "oracle",
    "erp",
    "crm",
    "project management",
    "product management",
    "product strategy",
    "agile",
    "scrum",
    "kanban",
    "prince2",
    "pmp",
    "six sigma",
    "process improvement",
    "business analysis",
    "requirements gathering",
    "stakeholder management",
    "risk management",
    "budgeting",
    "forecasting",
    "financial analysis",
    "accounting",
    "audit",
    "bookkeeping",
    "tax",
    "marketing",
    "digital marketing",
    "seo",
    "sem",
    "content strategy",
    "copywriting",
    "email marketing",
    "social media",
    "growth",
    "brand management",
    "ui",
    "ux",
    "figma",
    "sketch",
    "adobe xd",
    "photoshop",
    "illustrator",
    "invision",
    "wireframing",
    "prototyping",
    "user research",
    "usability testing",
    "customer support",
    "customer service",
    "client relations",
    "bpo",
    "call center",
    "operations management",
    "logistics",
    "supply chain",
    "inventory management",
    "procurement",
    "vendor management",
    "quality assurance",
    "qa",
    "manual testing",
    "automation testing",
    "selenium",
    "cypress",
    "rest",
    "soap",
    "api testing",
    "performance testing",
    "jmeter",
    "loadrunner",
    "curriculum development",
    "classroom management",
    "training",
    "facilitation",
    "coaching",
    "mentoring",
    "healthcare",
    "patient care",
    "clinical research",
    "nursing",
    "emr",
    "electronic medical records",
    "pharmacy",
    "pharmaceuticals",
    "compliance",
    "regulatory",
    "legal research",
    "litigation",
    "contracts",
    "negotiation",
    "public relations",
    "communication",
    "presentation",
    "leadership",
    "team management",
    "people management",
    "hiring",
    "talent acquisition",
    "interviewing",
    "onboarding",
    "training and development",
    "hr operations",
    "payroll",
    "benefits",
    "data entry",
    "office administration",
    "calendar management",
    "travel coordination",
    "event management",
    "scheduling",
    "problem solving",
    "critical thinking",
    "time management",
    "analytical skills",
    "presentation skills",
    "reporting",
    "documentation",
    "research",
}

SKILL_PATTERN = re.compile(
    r"(?i)\b("
    + "|".join(re.escape(term) for term in sorted(SKILL_TERMS, key=len, reverse=True))
    + r")\b"
)


def extract_skills(text: str) -> List[str]:
    """Return a deduplicated, order-preserving list of skill mentions."""
    seen: Set[str] = set()
    skills: List[str] = []
    for match in SKILL_PATTERN.finditer(text):
        skill = match.group(0).lower()
        if skill not in seen:
            seen.add(skill)
            skills.append(skill)
    return skills


def extend_skills(extra_terms: Iterable[str]) -> None:
    """Allow callers to extend the skill vocabulary at runtime."""
    for term in extra_terms:
        term = term.strip().lower()
        if term:
            SKILL_TERMS.add(term)
