# Generated by Django 5.2.4 on 2026-01-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_application',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_job',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='savedfilter',
            name='user',
        ),
        migrations.DeleteModel(
            name='CVUpload',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='SavedFilter',
        ),
    ]
