# Generated by Django 5.2.4 on 2026-01-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_remove_notification_related_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='offer_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
