# Generated by Django 5.2.4 on 2026-02-07 14:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='JobEducationRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree_level', models.CharField(choices=[('high_school', 'High School'), ('associate', 'Associate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('any', 'Any')], max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_requirements', to='myapi.job')),
            ],
            options={
                'db_table': 'job_education_requirements',
            },
        ),
        migrations.CreateModel(
            name='JobExperienceRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_years', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('max_years', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('seniority_levels', models.JSONField(blank=True, default=list, help_text="e.g., ['entry', 'mid', 'senior']")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_requirements', to='myapi.job')),
            ],
            options={
                'db_table': 'job_experience_requirements',
            },
        ),
        migrations.CreateModel(
            name='JobKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='myapi.job')),
            ],
            options={
                'db_table': 'job_keywords',
                'unique_together': {('job', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=100)),
                ('skill_type', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework'), ('tool', 'Tool'), ('soft_skill', 'Soft Skill')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('proficiency_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='myapi.job')),
            ],
            options={
                'db_table': 'job_skills',
                'unique_together': {('job', 'skill_name', 'skill_type')},
            },
        ),
    ]
