# Generated by Django 5.2.4 on 2026-02-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_user_avatar_url_jobeducationrequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexperiencerequirement',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobkeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobkeyword',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobskill',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='selection_process',
            field=models.JSONField(blank=True, null=True, default=list),
        ),
        migrations.DeleteModel(
            name='JobEducationRequirement',
        ),
        migrations.DeleteModel(
            name='JobExperienceRequirement',
        ),
        migrations.DeleteModel(
            name='JobKeyword',
        ),
        migrations.DeleteModel(
            name='JobSkill',
        ),
    ]
