# Generated by Django 6.0.3 on 2026-03-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_drop_hr_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='test_deadline_days',
            field=models.IntegerField(blank=True, default=3, help_text='Days to complete test after application', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='test_no_of_questions',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='test_time_allowed',
            field=models.IntegerField(blank=True, default=60, help_text='Time allowed in minutes', null=True),
        ),
    ]
