# Generated by Django 4.2.29 on 2026-03-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_application_test_completed_at_application_test_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
