# Generated by Django 5.2.8 on 2026-03-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_remove_application_test_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interview_recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
