# Generated by Django 5.2.4 on 2026-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_user_interview_recording_url_user_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_transcript',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
