# Generated by Django 5.2.4 on 2026-04-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_add_interview_fields_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
