# Generated by Django 5.2.4 on 2026-04-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_add_confidence_score_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
