# Generated by Django 5.2.4 on 2026-04-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_add_interview_recording_url_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
