# Generated by Django 4.2.29 on 2026-04-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_interview_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='available_positions',
            field=models.IntegerField(blank=True, default=1, help_text='Number of open positions / seats for this job', null=True),
        ),
    ]
