# Generated by Django 6.0.3 on 2026-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_job_test_deadline_days_job_test_no_of_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='test_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
