# Generated by Django 5.2.8 on 2026-03-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_add_test_started_at_to_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='test_started_at',
        ),
    ]
